# Generated by Django 4.1.1 on 2022-09-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coords',
            name='busno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
