# Generated by Django 4.1.1 on 2022-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0003_alter_coords_lat_alter_coords_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coords',
            name='ide',
            field=models.IntegerField(null=True),
        ),
    ]
