# Generated by Django 4.1.1 on 2022-10-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0005_remove_coords_ide_alter_coords_lat_alter_coords_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coords',
            name='lon',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
