# Generated by Django 4.1.1 on 2022-10-04 06:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0007_alter_coords_lat_alter_coords_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=9, max_digits=10), size=None), size=None)),
                ('routeno', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='coords',
            old_name='busno',
            new_name='routeno',
        ),
    ]
