# Generated by Django 4.1.1 on 2022-10-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0008_routes_rename_busno_coords_routeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
