# Generated by Django 4.1.1 on 2022-10-04 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0009_alter_routes_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=19, max_digits=20), size=2), size=5000),
        ),
    ]
