# Generated by Django 4.1.1 on 2022-10-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0010_alter_routes_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route',
            field=models.JSONField(null=True),
        ),
    ]
