# Generated by Django 4.1.1 on 2022-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0011_alter_routes_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=15),
        ),
        migrations.AlterField(
            model_name='coords',
            name='lon',
            field=models.DecimalField(decimal_places=14, max_digits=15),
        ),
    ]
