# Generated by Django 4.1.1 on 2022-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0012_alter_coords_lat_alter_coords_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='lat',
            field=models.DecimalField(decimal_places=18, max_digits=19),
        ),
        migrations.AlterField(
            model_name='coords',
            name='lon',
            field=models.DecimalField(decimal_places=18, max_digits=19),
        ),
    ]
