# Generated by Django 4.1.1 on 2022-10-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0015_alter_coords_lat_alter_coords_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='busstops',
            field=models.JSONField(null=True),
        ),
    ]
