# Generated by Django 4.1.1 on 2022-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0017_alter_routes_routeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='routeno',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
