# Generated by Django 4.1.1 on 2022-10-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0018_alter_coords_routeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='routeno',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
