# Generated by Django 4.1.1 on 2022-10-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30, null=True)),
                ('busno', models.CharField(max_length=60, null=True)),
                ('stopname', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
