# Generated by Django 4.1.1 on 2022-10-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_busno_busno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busno',
            name='busno',
            field=models.CharField(default='Bus No : 1 Tiruvotriyur', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='busno',
            name='stopname',
            field=models.CharField(default='Lift Gate', max_length=70, null=True),
        ),
    ]
