# Generated by Django 4.1.1 on 2022-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_busno_busno_alter_busno_stopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busno',
            name='busno',
            field=models.CharField(default='"Bus No : 1 Tiruvotriyur"', max_length=60, null=True),
        ),
    ]
