# Generated by Django 4.1.1 on 2022-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_busno_busno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busno',
            name='stopname',
            field=models.CharField(default='"Lift Gate"', max_length=70, null=True),
        ),
    ]
